baseURL = "https://bcnelson.github.io/SSH-Wiki-Example/"
languageCode = "en-us"
title = "Self-Hosted Show Wiki"

theme = "learn"
[params]
themeVariant = "orange"

# For search functionality
[outputs]
home = [ "HTML", "RSS", "JSON"]
